<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { SerialFlowControl, SerialParity, type SerialConfig } from '../serial/serial-types'
import { catalogApi, type CatalogDetail } from '../device-catalog/catalog-api'
import type { AppRoute } from '../device-catalog/catalog-route'
import { TestGroupApiError, testGroupApi, type TestGroup } from '../test-groups/test-group-api'
interface EditableNode { name: string; catalogKey: string; catalogRevision: number; slaveId: number }
const props = defineProps<{ readonly groupId?: number }>(); const emit = defineEmits<{ navigate: [route: AppRoute] }>()
const catalogs = ref<readonly CatalogDetail[]>([]); const existing = ref<TestGroup | null>(null); const name = ref('새 테스트 그룹'); const baudRate = ref(9600); const nodes = reactive<EditableNode[]>([]); const error = ref<string | null>(null); const saving = ref(false)
const baudOptions = computed(() => { const selected = nodes.map((node) => catalogs.value.find(({ catalogKey }) => catalogKey === node.catalogKey)).filter((item) => item !== undefined); if (!selected.length) return [9600]; return selected.map(({ definition }) => definition.profile.serial.supportedBaudRates).reduce((common, values) => common.filter((value) => values.includes(value))) })
async function load(): Promise<void> { try { const summaries = (await catalogApi.list()).items.filter(({ enabled }) => enabled); catalogs.value = await Promise.all(summaries.map(({ catalogKey }) => catalogApi.get(catalogKey))); if (props.groupId) { existing.value = await testGroupApi.get(props.groupId); name.value = existing.value.name; baudRate.value = existing.value.serialConfig.baudRate; nodes.push(...existing.value.nodes.map(({ name: nodeName, catalogKey, catalogRevision, slaveId }) => ({ name: nodeName, catalogKey, catalogRevision, slaveId }))) } if (!nodes.length) addNode() } catch { error.value = '그룹 편집 정보를 불러오지 못했습니다.' } }
function addNode(): void { const catalog = catalogs.value[0]; if (!catalog) return; nodes.push({ name: '', catalogKey: catalog.catalogKey, catalogRevision: catalog.revision, slaveId: catalog.definition.profile.slave.defaultId }); if (!baudOptions.value.includes(baudRate.value)) baudRate.value = baudOptions.value[0] ?? 9600 }
function catalogChanged(node: EditableNode): void { const catalog = catalogs.value.find(({ catalogKey }) => catalogKey === node.catalogKey); if (!catalog) return; node.catalogRevision = catalog.revision; node.slaveId = catalog.definition.profile.slave.defaultId; if (!baudOptions.value.includes(baudRate.value)) baudRate.value = baudOptions.value[0] ?? catalog.definition.profile.serial.default.baudRate }
function move(index: number, offset: number): void { const target = index + offset; if (target < 0 || target >= nodes.length) return; const [node] = nodes.splice(index, 1); nodes.splice(target, 0, node) }
async function save(): Promise<void> { error.value = null; if (!nodes.length || !baudOptions.value.includes(baudRate.value) || new Set(nodes.map(({ slaveId }) => slaveId)).size !== nodes.length) { error.value = '공통 baudrate와 중복되지 않는 Slave ID를 확인해 주세요.'; return } saving.value = true; const serialConfig: SerialConfig = { baudRate: baudRate.value, dataBits: 8, stopBits: 1, parity: SerialParity.None, flowControl: SerialFlowControl.None }; try { const input = { name: name.value, serialConfig, nodes }; const saved = existing.value ? await testGroupApi.update(existing.value, input) : await testGroupApi.create(input); emit('navigate', { page: 'test-group-run', groupId: saved.id }) } catch (caught) { error.value = caught instanceof TestGroupApiError && caught.code === 'TEST_GROUP_REVISION_CONFLICT' ? '다른 화면에서 그룹이 수정되었습니다. 새로고침한 뒤 다시 변경해 주세요.' : '그룹을 저장하지 못했습니다. Catalog revision과 입력 범위를 확인해 주세요.' } finally { saving.value = false } }
onMounted(load)
</script>
<template>
  <header class="page-heading detail-page-heading"><div><button class="text-link" type="button" @click="emit('navigate', { page: 'test-group-list' })">← 그룹 목록</button><p class="eyebrow">TEST GROUP EDITOR</p><h1>{{ groupId ? '테스트 그룹 수정' : '새 테스트 그룹' }}</h1></div></header>
  <p v-if="error" class="notice error">{{ error }}</p>
  <form class="surface-card test-group-editor" @submit.prevent="save"><div class="test-group-base-fields"><label>그룹 이름<input v-model="name" required maxlength="100" /></label><label>공통 baudrate<select v-model.number="baudRate"><option v-for="baud in baudOptions" :key="baud" :value="baud">{{ baud.toLocaleString() }}</option></select><small>모든 node Catalog가 함께 지원하는 속도만 표시합니다.</small></label></div>
    <div class="section-heading test-group-node-heading"><div><h2>테스트 node</h2><p>Slave ID는 같은 버스에서 중복될 수 없습니다.</p><button class="button button-ghost button-small" type="button" @click="addNode">node 추가</button></div></div>
    <div class="group-node-editor-list"><article v-for="(node, index) in nodes" :key="index"><strong>{{ index + 1 }}</strong><label>이름<input v-model="node.name" required maxlength="100" /></label><label>Catalog<select v-model="node.catalogKey" @change="catalogChanged(node)"><option v-for="catalog in catalogs" :key="catalog.catalogKey" :value="catalog.catalogKey">{{ catalog.title }}</option></select></label><label>Slave ID<input v-model.number="node.slaveId" type="number" min="1" max="247" required /></label><div class="inline-actions"><button type="button" class="button button-ghost button-small" :disabled="index === 0" @click="move(index, -1)">↑</button><button type="button" class="button button-ghost button-small" :disabled="index === nodes.length - 1" @click="move(index, 1)">↓</button><button type="button" class="button danger button-small" :disabled="nodes.length === 1" @click="nodes.splice(index, 1)">삭제</button></div></article></div>
    <div class="editor-actions"><button class="button button-ghost" type="button" @click="emit('navigate', { page: 'test-group-list' })">취소</button><button class="button button-primary" type="submit" :disabled="saving">{{ saving ? '저장 중…' : '저장' }}</button></div>
  </form>
</template>
